import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Link from 'next/link'

import { ReactQueryProvider } from '@/providers/ReactQueryProvider'

import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-gray-100 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>{children}</ReactQueryProvider>

        <footer className="text-center text-muted-foreground text-sm mt-8">
          <p>
            <Link
              className="hover:text-black hover:underline"
              href="
https://javierperez.com?utm_sourcefitnesspark-ical&utm_medium=footer&utm_campaign=fitnesspark-ical"
              target="_blank"
              rel="noopener noreferrer"
            >
              &copy; {new Date().getFullYear()} Javier Pérez
            </Link>
          </p>
        </footer>
      </body>
    </html>
  )
}
